const mongoose = require('mongoose');
const Refinement = require('../models/ImageRefinement');
const Product = require('../models/Product');
const Job = require('../models/BackgroundJob');
const Usage = require('../models/AiUsageBucket');
const { createFeatureReadiness, inspectFeatureReadiness } = require('./adminFeatureReadiness');
const { createBackgroundJobService } = require('./backgroundJobService');
const { createImageRefinementAdapter } = require('./imageRefinementAdapter');
const { createImageRefinementService } = require('./imageRefinementService');
const { createImageRefinementWorkers } = require('./imageRefinementWorkers');
const { createImageStudioInitializer } = require('./imageStudioDatabaseSetup');
const images = createImageRefinementAdapter({ http: require('axios'), cloudinary: require('../utils/cloudinary') });
const queue = createBackgroundJobService({ Job, allowedTypes: ['image.refine', 'image.publish'] });
const service = createImageRefinementService({ Refinement, Product, Job, Usage, queue, images, connection: mongoose.connection });
const ready = createFeatureReadiness({ models: [Refinement, Job, Usage] });
const inspectReadiness = () => inspectFeatureReadiness({ models: [Refinement, Job, Usage] });
const handlers = () => createImageRefinementWorkers({ Refinement, Product, service, images });
const initializeDatabase = createImageStudioInitializer({ getDatabase: () => mongoose.connection.db });
module.exports = { service, ready, inspectReadiness, handlers, initializeDatabase };
